### ISSUE TITLE
AdGem crashes instantly after the app launch [only if minifyEnabled is set to true]

### ISSUE THREAD

**Issue by AiwNexT** [AdGem/Android-Example#15]
AdGem library works fine without Proguard (minifyEnabled=false), but with Proguard enabled there is a crash. 
AdGem version: 3.0.1
Crash occurs on different Android versions each time the app is launched.
I would mention that the crash occurs earlier than `AdGem.get()` is being called.

So, here are the logs:
`Fatal Exception: java.lang.NullPointerException
       at com.adgem.android.internal.g$a.onResponse(g.java:2)
       at com.adgem.android.internal.g$c.onResponse(g.java:13)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:20)
       at androidx.emoji2.text.EmojiCompatInitializer$BackgroundDefaultLoader$$InternalSyntheticLambda$0$9100475115e8089aa3f5bd60914a597a04bd55ac33c771ff0e0a94e91b452f2e$0.run$bridge(EmojiCompatInitializer.java:20)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)`

**Comment by makinaman** [comment]
The same happens to me.
Also with AdGem version: 3.0.1
With Proguard (minifyEnabled=true) the app crashes every time it loads, before calling AdGem.get().

`FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.adgem.android.internal.g$a.onResponse(Unknown Source:2)
        at com.adgem.android.internal.g$c.onResponse(Unknown Source:13)`

**Comment by nhaynes** [comment]
Sorry for the inconvenience, we have a developer looking into the issue.

**Comment by AiwNexT** [comment]
@nhaynes Do you have a planned date when you plan to release the updated AdGem SDK?

**Comment by AiwNexT** [comment]
Will anybody take a look at the issue? It seems like it's still not resolved

**Comment by makinaman** [comment]
I have an application waiting for them to fix this so I can integrate the SDK.

**Comment by NedkoBrymchev** [comment]
Any update here?

**Comment by AiwNexT** [comment]
Guys, I'm constantly trying to contact their support, but they are simply ignoring me. I think that it might be that the company (or the product) has reached an EOL. And even if it hasn't, what's the point of monetising with the company that doesn't give a damn about its clients and the quality of its products?

**Comment by Exaper** [comment]
Hi thread! Thanks for filing out the issue with us. The crash should be fixed in v3.2.0.

**Comment by Exaper** [comment]
Please refer to https://github.com/AdGem/Android-Example/issues/18
