### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException only happening on signed apk

### ISSUE THREAD

**Issue by vinicbr** [AdGem/Android-Example#18]
```
Fatal Exception: java.lang.NullPointerException:
       at com.adgem.android.internal.g$a.onResponse(g.java:2)
       at com.adgem.android.internal.g$c.onResponse(g.java:13)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8302)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

I'm facing a weird issue on release build in my app. Works fine in debug version, but when I generate a signed apk, the app crashes. I did some research and saw that I'm not the only one with this problem.

In buildTypes (build.gradle(:app)), minifyEnabled is true in both debug and release.

build.gradle file:

```
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

```
I've already tried:
- Rebuild
- Clean
- Invalidate and restart
- Added proguard of adgem

**Comment by Exaper** [comment]
HI @vinicbr. Could you mention version of SDK you are running this with? Are you using the latest version?

**Comment by vinicbr** [comment]
Hello @Exaper.I'm using v3.2.0

**Comment by vinicbr** [comment]
I see now that my issue was similar to the #16. So I changed 

> proguard-android-optimize.txt

 to 

> proguard-android.txt

 and now it's working fine.

I just don't understand why in previous SDK versions like 2.5.0 this wasn't an issue.

**Comment by Exaper** [comment]
It's due to our internal dependencies that we've upgraded. Thanks for reporting this issue to us. I will go ahead and close it.
