### ISSUE TITLE
Crash attempting to show Offer Wall

### ISSUE THREAD

**Issue by Exaper** [AdGem/Android-Example#3]
Redundant calls to `AdGem.showOfferWall()` may produce a crash v0.9.3) with:

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWallActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6904)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3269)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3418)
       at android.app.ActivityThread.access$1100(ActivityThread.java:231)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by isamotiuc** [comment]
@Exaper Hello, we yesterday made update to v0.9.5, and unfortunately we experience the same crash.

**Comment by Exaper** [comment]
@isamotiuc can you post exact stacktrace of the crash in v0.9.5? Thanks!

**Comment by isamotiuc** [comment]
Yes, sure
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWallActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6742)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by isamotiuc** [comment]
@Exaper Any news regarding this issue? Unfortunatly it is our top issue for now.

**Comment by Exaper** [comment]
@isamotiuc please upgrade to v0.9.8 and see if the issue is still there. Thanks for reporting this to us!
